# Generated by Django 5.0.6 on 2024-06-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_description',
            new_name='service_des',
        ),
    ]
