# Generated by Django 5.0.6 on 2024-06-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
                ('referral', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('occassion', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', max_length=3)),
                ('budget', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
    ]
